### ISSUE TITLE
False negatives in test results

### ISSUE THREAD

**Issue by tristandeleu** [pg2455/covid_p2p_simulation#111]
False negatives are generated based on the `P_FALSE_NEGATIVE ` of the test
https://github.com/pg2455/covid_p2p_simulation/blob/62c7e416c803ed9f00e8f561b6bdb69a2d9ff800/simulator.py#L460-L463
If `P_FALSE_NEGATIVE = 0`, then this means that the result will always be negative, which is not what is expected. I think `>` should be `<`.

@teganmaharaj

**Comment by pg2455** [comment]
It is definitely a bug! thanks for reporting that.

**Comment by pg2455** [comment]
Fixed in `develop` now!
