### ISSUE TITLE
Missed update days on human (RuntimeWarning)

### ISSUE THREAD

**Issue by schuberm** [pg2455/covid_p2p_simulation#139]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

Please describe the behavior you are expecting

# Current Behavior

What is the current behavior?

`/usr/local/lib/python3.7/site-packages/covid19sim/simulator.py:632: RuntimeWarning: Missed 19 update days on human:882. Current day 2020-04-25 18:19:43.300211, last_date['run'] 2020-04-05
  RuntimeWarning)`

I'm not sure where to start on this one...

**Comment by pg2455** [comment]
This used to happen when a person is hospitalized. It has now been moved to City ([here](https://github.com/pg2455/covid_p2p_simulation/blob/experimental/src/covid19sim/base.py#L422)), where there will be no updates that can be missed.
