### ISSUE TITLE
Issue with log_test

### ISSUE THREAD

**Issue by gabrielhuang** [pg2455/covid_p2p_simulation#26]
![image](https://user-images.githubusercontent.com/7798468/78715860-fd449780-78eb-11ea-9411-ce9f7eaad14e.png)

log_test arguments for time and result are swapped.
the resulting produced timestamps contain "True" and "False" instead of datetime objects

**Comment by pg2455** [comment]
thanks for pointing that out!  It should be changed ASAP.

**Comment by nasimrahaman** [comment]
This seems to be fixed, closing the issue. 👍
