### ISSUE TITLE
Humans are never recovered

### ISSUE THREAD

**Issue by ghost** [pg2455/covid_p2p_simulation#41]
During the course of the disease, a human should go through four stages :
- susceptible
- exposed
- infectious
- removed (recovered or dead)

This is not reflected in the current implementation. See [these](https://github.com/pg2455/covid_p2p_simulation/blob/7c23bcd200bcf5c86d582838267421550b765934/simulator.py#L293-L299) lines:
```python
            if self.is_infectious and self.env.timestamp - self.infection_timestamp >= datetime.timedelta(days=self.recovery_days):
                if self.never_recovers or True: # re-infection assumed negligble
                    self.recovered_timestamp = datetime.datetime.max
                    dead = True
                else:
                    self.recovered_timestamp = self.env.timestamp
                    dead = False
```
The second condition (`if self.never_recovers or True`) marks every individual as `dead`. [Later](https://github.com/pg2455/covid_p2p_simulation/blob/7c23bcd200bcf5c86d582838267421550b765934/simulator.py#L303-L306) this makes the `log_recovery` method unreachable:
```python
                if dead:
                    yield self.env.timeout(np.inf)


                Event.log_recovery(self, self.env.timestamp, dead)
```

Moreover, [these](https://github.com/pg2455/covid_p2p_simulation/blob/7c23bcd200bcf5c86d582838267421550b765934/simulator.py#L167-L169) lines:
```python
    @property
    def is_removed(self):
        return self.recovered_timestamp == datetime.datetime.max
```
should be:
```python
    @property
    def is_removed(self):
        return self.recovered_timestamp != datetime.datetime.min
```

Finally, `next_state` in [these](https://github.com/pg2455/covid_p2p_simulation/blob/7c23bcd200bcf5c86d582838267421550b765934/simulator.py#L268-L273) lines:
```python
    def assert_state_changes(self):
        next_state = {0:1, 1:2, 2:0}
        assert sum(self.state) == 1, f"invalid compartment for human:{self.name}"
        if self.last_state != self.state:
            assert next_state[self.last_state.index(1)] == self.state.index(1), f"invalid compartment transition for human:{self.name}"
            self.last_state = self.state
```
should change into `{0:1, 1:2, 2:3}`.

**Comment by mweiss17** [comment]
Hey -- thanks for catching this bug. PR has been submitted to address it here: https://github.com/pg2455/covid_p2p_simulation/pull/42
