### ISSUE TITLE
keeping `.pkl` files  and other heavy files in `.gitignore`

### ISSUE THREAD

**Issue by pg2455** [pg2455/covid_p2p_simulation#49]
If `.pkl` or other heavy files are not required, can we keep them out of the repo? if we keep piling up `.pkl` files, the repo will become unmanageable.

**Comment by mweiss17** [comment]
agreed -- I removed them in my privacy branch.
I see that you did as well in the PR you submitted!
Once one of these is merged, it will no longer be a probem :)
