### ISSUE TITLE
Older people never get really sick

### ISSUE THREAD

**Issue by tristandeleu** [pg2455/covid_p2p_simulation#67]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

The risk of being really sick should increase with age (or at least should be non zero).

# Current Behavior

The risk of being really sick (a property of `Human`) is dependent on the age. Currently, individuals with `age > 20` can never be `gets_really_sick = True`.
https://github.com/pg2455/covid_p2p_simulation/blob/a7acbbe4c8b3fe3c4bf7f427725f6964273e93d8/simulator.py#L93

**Comment by pg2455** [comment]
@teganmaharaj  - Do you have a source for that?

**Comment by teganmaharaj** [comment]
This is legacy code (I think it's something Marie or Marco implemented very early on); I will check the spreadsheet of epi data and update this to something more realistic.

**Comment by teganmaharaj** [comment]
Fixed in the #symptom_fixes branch, to be merged soon. Thanks for raising!
