### ISSUE TITLE
Older people are more asymptomatic

### ISSUE THREAD

**Issue by tristandeleu** [pg2455/covid_p2p_simulation#68]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior

The risk of being asymptomatic should be higher than the baseline (0.5 in the comment, 0.2 in config) for younger people, and lower than the baseline for older people.

# Current Behavior

The risk of being asymptomatic is higher for older people and lower for younger people, with children younger than 10 never being asymptomatic.
https://github.com/pg2455/covid_p2p_simulation/blob/a7acbbe4c8b3fe3c4bf7f427725f6964273e93d8/simulator.py#L100-L102

**Comment by pg2455** [comment]
Thanks! I think it should be `self.rng.rand() < (BASELINE_P_ASYMPTOMATIC - (self.age - 50) * 0.5) / 100 ` @teganmaharaj  Do you agree?

**Comment by teganmaharaj** [comment]
Yes, you're both right! I'll fix this, good catch and sorry about that!!

Worked out example in case it helps someone else:
===========
if you're 20:
asymptomatic = (50 - (20-50)/2 ) /100 = (50 + 15) /100 # 65% chance of being asymptomatic

if you're 70:
asymptomatic = (50 - (70-50)/2 ) /100 = (50 - 15) /100 # 35% chance of being asymptomatic
