### ISSUE TITLE
Normalize the format for human field

### ISSUE THREAD

**Issue by tristandeleu** [pg2455/covid_p2p_simulation#9]
Is it possible to remove the `other_` prefix for the `human1` and `human2` fields in `log_encounter`? This would allow consistency when accessing the properties of either individual. 
https://github.com/pg2455/covid_p2p_simulation/blob/a92fc82052e5cb4c9d5a45cc908696b1c6c60a4d/simulator.py#L106

**Comment by pg2455** [comment]
I have fixed that thing. The new payload is also updated on the documents. The changes are in the branch - prateek_changes. I am waiting for the reviewers to review it and merge it to the master.

**Comment by pg2455** [comment]
The changes are in `master` now.
